table F_FleetPlan
	lineageTag: 483ebb66-7c5e-5343-9a41-3ceb2239afa2

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: e279c7b4-a6c1-53ed-b9d4-51c3373b9bdf
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column AircraftKey
		dataType: string
		isHidden
		lineageTag: 2cb79b35-3d5e-5d1f-8e76-a21a84dafe33
		summarizeBy: none
		sourceColumn: AircraftKey

		annotation SummarizationSetBy = Automatic

	column NetChange
		dataType: int64
		formatString: #,0
		lineageTag: 1eaa69cb-860c-5965-8066-09b67c3f31c2
		summarizeBy: none
		sourceColumn: NetChange

		annotation SummarizationSetBy = Automatic

	column Deliveries
		dataType: int64
		formatString: #,0
		lineageTag: 1f76bd92-b3c8-5f33-a9f0-b7d20ca1124b
		summarizeBy: none
		sourceColumn: Deliveries

		annotation SummarizationSetBy = Automatic

	column Retirements
		dataType: int64
		formatString: #,0
		lineageTag: e41e8ac0-40c3-592f-b36b-a7585de914eb
		summarizeBy: none
		sourceColumn: Retirements

		annotation SummarizationSetBy = Automatic

	partition F_FleetPlan = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DossierDonnees & "\F_FleetPlan.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Types = Table.TransformColumnTypes(Entetes, {{"FiscalYear", Int64.Type}, {"AircraftKey", type text}, {"NetChange", Int64.Type}, {"Deliveries", Int64.Type}, {"Retirements", Int64.Type}}, "en-US")
				in
				    Types

	annotation PBI_ResultType = Table
