table F_Freight
	lineageTag: 2cc3d08e-f079-5a3b-b42a-43bb76209202

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: bc7b9e61-f8cd-5ee0-b676-178ee129c657
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column ShipmentsPerDay
		dataType: int64
		formatString: #,0
		lineageTag: 00d59e26-c7c0-5c46-a8a0-513713ced074
		summarizeBy: none
		sourceColumn: ShipmentsPerDay

		annotation SummarizationSetBy = Automatic

	column RevenuePerShipment
		dataType: double
		formatString: $#,0.00
		lineageTag: 7888acc9-9beb-577a-904b-7c60a9fa3216
		summarizeBy: none
		sourceColumn: RevenuePerShipment

		annotation SummarizationSetBy = Automatic

	column WeightPerShipmentLbs
		dataType: int64
		formatString: #,0
		lineageTag: 8ddfd09c-d607-51ee-954e-1a223dd28669
		summarizeBy: none
		sourceColumn: WeightPerShipmentLbs

		annotation SummarizationSetBy = Automatic

	partition F_Freight = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DossierDonnees & "\F_Freight.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Types = Table.TransformColumnTypes(Entetes, {{"FiscalYear", Int64.Type}, {"ShipmentsPerDay", Int64.Type}, {"RevenuePerShipment", type number}, {"WeightPerShipmentLbs", Int64.Type}}, "en-US")
				in
				    Types

	annotation PBI_ResultType = Table
