table F_Geography
	lineageTag: 616d1bac-a3b7-5d1e-ac40-edde5955893b

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: cbf9cfaf-b241-5967-af95-cf34d02e034f
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = Automatic

	column Geography
		dataType: string
		lineageTag: 567ec9d9-9e61-5d71-9102-79016341a84c
		summarizeBy: none
		sourceColumn: Geography

		annotation SummarizationSetBy = Automatic

	column Revenue
		dataType: int64
		formatString: #,0
		lineageTag: d55f9d43-afa3-5e53-aa44-f4d0fae46408
		summarizeBy: none
		sourceColumn: Revenue

		annotation SummarizationSetBy = Automatic

	partition F_Geography = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DossierDonnees & "\F_Geography.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Entetes = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Types = Table.TransformColumnTypes(Entetes, {{"FiscalYear", Int64.Type}, {"Geography", type text}, {"Revenue", Int64.Type}}, "en-US")
				in
				    Types

	annotation PBI_ResultType = Table
